# Generated by Django 3.1 on 2020-09-03 12:53

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20200903_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[500, 300], upload_to='products/%Y/%m/%d'),
        ),
    ]
