# Generated by Django 3.1 on 2020-09-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_orderitem_braintree_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='braintree_id',
        ),
        migrations.AddField(
            model_name='order',
            name='braintree_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
